version: "3.7"

services:
  db:
    container_name: jog_tracker_db
    image: postgres:14.4-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jog
      - POSTGRES_PASSWORD=jog
      - POSTGRES_DB=jog
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test:
        ["CMD", "pg_isready", "-q", "-d", "jog", "-U", "jog"]
      timeout: 45s
      interval: 10s
      retries: 10

  backend:
    container_name: jog_tracker_backend
    build: .
    restart: always
    env_file: ./jog_tracker/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery_worker:
    container_name: jog_tracker_celery_worker
    build: .
    command: celery -A jog_tracker worker -l info -c 2 -E -n default_worker@%h
    env_file: ./jog_tracker/.env
    depends_on:
      - db
      - redis
    healthcheck:
      test: celery -A jog_tracker inspect ping -t 3 || exit 1
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 30s

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

volumes:
  postgres_data:
